// Resolve a public/ asset path against Vite's base URL so media works both in
// dev ('/') and on GitHub Pages ('/nastionion/'). Store paths without a leading
// slash, e.g. asset('media/wal-design/clip.mp4').
export const asset = (path: string) =>
  `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`

// The AV1 .webm sibling of an .mp4 path (generated by scripts/make-av1.sh).
export const webm = (path: string) => asset(path.replace(/\.mp4$/, '.webm'))

// Whether this browser can play our AV1-in-WebM clips. Detected once, in JS,
// rather than via <source> fallback — Safari's multi-source selection is flaky
// with autoplay-on-scroll (it can error instead of falling through to the MP4).
let _av1: boolean | null = null
const supportsAV1 = () => {
  if (_av1 === null) {
    _av1 =
      typeof document !== 'undefined' &&
      document.createElement('video').canPlayType('video/webm; codecs="av01.0.05M.08"') !== ''
  }
  return _av1
}

// The best single video source for this browser: AV1 WebM where supported
// (Chrome/Firefox/Edge/Android), otherwise the universal H.264 MP4 (Safari/iOS).
export const bestVideo = (mp4Path: string) => (supportsAV1() ? webm(mp4Path) : asset(mp4Path))
